---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  # Default policy - deny all
  policy.default: role:readonly
  
  # Admin role - full access
  policy.csv: |
    p, role:admin, applications, *, */*, allow
    p, role:admin, clusters, *, *, allow
    p, role:admin, repositories, *, *, allow
    p, role:admin, certificates, *, *, allow
    p, role:admin, projects, *, *, allow
    p, role:admin, accounts, *, *, allow
    p, role:admin, gpgkeys, *, *, allow
    p, role:admin, logs, *, *, allow
    p, role:admin, exec, *, *, allow
    p, role:admin, settings, *, *, allow
    
    # Readonly role - view only
    p, role:readonly, applications, get, */*, allow
    p, role:readonly, clusters, get, *, allow
    p, role:readonly, repositories, get, *, allow
    p, role:readonly, certificates, get, *, allow
    p, role:readonly, projects, get, *, allow
    p, role:readonly, logs, get, *, allow
    
    # Built-in admin gets admin role
    g, admin, role:admin
    
    # User assignments  
    g, brandon, role:admin
    g, readonly, role:readonly