---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-homelab
  namespace: cert-manager
spec:
  secretName: wildcard-homelab-tls
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  commonName: "*.homelab"
  dnsNames:
  - "*.homelab"
  - "homelab"