---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-opsguy-io
  namespace: cert-manager
spec:
  secretName: wildcard-opsguy-io-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.opsguy.io"
  dnsNames:
  - "*.opsguy.io"
  - "opsguy.io"