apiVersion: v1
kind: Pod
metadata:
  name: data-copy
spec:
  nodeName: pi5-2
  containers:
  - name: alpine
    image: alpine
    command: ["sleep", "3600"]
    volumeMounts:
    - name: pvc-volume
      mountPath: /data
    - name: hdd-mount
      mountPath: /mnt/data
  volumes:
  - name: pvc-volume
    persistentVolumeClaim:
      claimName: stash-stash-pvc
  - name: hdd-mount
    hostPath:
      path: /mnt/data
      type: Directory
  restartPolicy: Never
