replicaCount: 1

image:
  repository: stashapp/stash
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9999

ingress:
  enabled: true
  className: nginx
  host: stash.homelab

persistence:
  enabled: true
  size: 260Gi
  storageClass: longhorn

resources: {}
