---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homebridge
  namespace: homebridge
  labels:
    app: homebridge
spec:
  replicas: 1
  strategy:
    type: Recreate  # Prevents multi-attach errors with RWO volumes
  selector:
    matchLabels:
      app: homebridge
  template:
    metadata:
      labels:
        app: homebridge
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8581"
        prometheus.io/path: "/"
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: homebridge
        image: homebridge/homebridge:ubuntu
        ports:
        - containerPort: 8581
          name: web-ui
        env:
        - name: HOMEBRIDGE_CONFIG_UI
          value: "1"
        - name: HOMEBRIDGE_CONFIG_UI_PORT
          value: "8581"
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/New_York"
        volumeMounts:
        - name: homebridge-data
          mountPath: /homebridge
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
      volumes:
      - name: homebridge-data
        persistentVolumeClaim:
          claimName: homebridge-data