apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.12.1
    helm:
      values: |
        controller:
          service:
            type: LoadBalancer
            loadBalancerIP: 192.168.4.21

          ingressClassResource:
            default: true
            name: nginx  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
