---
image:
  repository: grafana/grafana
  tag: "11.0.0" 

persistence:
  enabled: true
  storageClassName: longhorn
  size: 5Gi

ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - grafana.opsguy.io
  tls:
    - hosts:
      - grafana.opsguy.io
      secretName: wildcard-opsguy-io-tls

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server.monitoring.svc.cluster.local
      access: proxy
      isDefault: false
    - name: Loki
      type: loki
      url: http://loki-stack.monitoring.svc.cluster.local:3100
      access: proxy
      isDefault: true
      jsonData:
        timeout: 60
        maxLines: 1000
        derivedFields: []
        # This is the important part for Grafana v12
        healthCheck:
          enabled: true
          target:
            # Use a simple LogQL query that Loki understands
            expr: "{job=\"host-logs\"} |= \"\""

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    # Node Exporter Full - most reliable and widely used
    node-exporter-full:
      gnetId: 1860
      revision: 37
      datasource: Prometheus
    
    # Kubernetes cluster monitoring - modern and well-maintained
    kubernetes-cluster:
      gnetId: 7249
      revision: 1
      datasource: Prometheus
    
    # K3s specific dashboard - optimized for K3s
    k3s-cluster:
      gnetId: 15282
      revision: 1
      datasource: Prometheus
    
    # Kubernetes Pod Resources - detailed pod monitoring
    kubernetes-pods:
      gnetId: 6417
      revision: 1
      datasource: Prometheus
    
    # Container monitoring via cAdvisor
    cadvisor-dashboard:
      gnetId: 14282
      revision: 1
      datasource: Prometheus
    
    # ArgoCD monitoring
    argocd-dashboard:
      gnetId: 19993
      revision: 2
      datasource: Prometheus
    
    # Loki logs dashboard
    loki-logs:
      gnetId: 13639
      revision: 2
      datasource: Loki
    
    # AlertManager dashboard
    alertmanager:
      gnetId: 9578
      revision: 4
      datasource: Prometheus

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

serviceMonitor:
  enabled: true