# Minimal homepage values file - only the overrides you need

# Use your external ConfigMap
config:
  useExistingConfigMap: "homepage-config"

# Enable ingress
ingress:
  main:
    enabled: true
    ingressClassName: nginx
    hosts:
      - host: home.homelab
        paths:
          - path: /
            pathType: Prefix

# Environment variable for allowed hosts
env:
  - name: HOMEPAGE_ALLOWED_HOSTS
    value: "home.homelab,localhost"

# Disable RBAC (override the default)
enableRbac: false

# Resource limits for Raspberry Pi
resources:
  requests:
    memory: 64Mi
    cpu: 50m
  limits:
    memory: 256Mi
    cpu: 200m