---
image:
  repository: ghcr.io/gethomepage/homepage
  pullPolicy: IfNotPresent
  # tag: v0.6.0

# TLS/HTTPS Configuration
ingress:
  main:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "selfsigned-issuer"
    ingressClassName: nginx
    hosts:
      - host: home.homelab
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - home.homelab
        secretName: homepage-tls

# Custom volume mounts using individual ConfigMaps
persistence:
  config:
    enabled: false # Disable default ConfigMap mount
  logs:
    enabled: true
    type: emptyDir
    mountPath: "/app/config/logs"

# Define custom volumes and volume mounts
volumes:
  - name: settings-config
    configMap:
      name: homepage-settings
  - name: services-config
    configMap:
      name: homepage-services
  - name: widgets-config
    configMap:
      name: homepage-widgets
  - name: bookmarks-config
    configMap:
      name: homepage-bookmarks
  - name: kubernetes-config
    configMap:
      name: homepage-kubernetes
  - name: logs
    emptyDir: {}

volumeMounts:
  - name: settings-config
    mountPath: /app/config/settings.yaml
    subPath: settings.yaml
  - name: services-config
    mountPath: /app/config/services.yaml
    subPath: services.yaml
  - name: widgets-config
    mountPath: /app/config/widgets.yaml
    subPath: widgets.yaml
  - name: bookmarks-config
    mountPath: /app/config/bookmarks.yaml
    subPath: bookmarks.yaml
  - name: kubernetes-config
    mountPath: /app/config/kubernetes.yaml
    subPath: kubernetes.yaml
  - name: logs
    mountPath: /app/config/logs

# Environment variables
env:
  - name: HOMEPAGE_ALLOWED_HOSTS
    value: "home.homelab,localhost"
  - name: TZ
    value: "America/Chicago"  # Set to your timezone

resources:
  requests:
    memory: "64Mi"
    cpu: "25m"
  limits:
    memory: "256Mi"
    cpu: "100m"