# Enable RBAC for Kubernetes integration
enableRbac: true

serviceAccount:
  create: true

# Use existing ConfigMap to avoid template loading issues
config:
  useExistingConfigMap: "homepage-config"

# Enable ingress
ingress:
  main:
    enabled: true
    ingressClassName: nginx
    hosts:
      - host: home.homelab
        paths:
          - path: /
            pathType: Prefix

# Environment variables
env:
  - name: HOMEPAGE_ALLOWED_HOSTS
    value: "home.homelab,localhost"

# Resources
resources:
  requests:
    memory: 128Mi
    cpu: 50m
  limits:
    memory: 512Mi
    cpu: 200m