# Homepage values without complex config (to isolate the issue)
image:
  repository: ghcr.io/gethomepage/homepage
  tag: v0.8.8

enableRbac: true

extraClusterRoles:
  - apiGroups: [""]
    resources: ["namespaces", "nodes", "pods", "services"]
    verbs: ["get", "list"]

serviceAccount:
  create: true

service:
  main:
    ports:
      http:
        port: 3000

ingress:
  main:
    enabled: true
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - host: home.homelab
        paths:
          - path: /
            pathType: Prefix

config:
  settings:
    title: "Homepage"
  kubernetes:
    mode: cluster

env:
  - name: HOMEPAGE_ALLOWED_HOSTS
    value: "home.homelab,localhost"
  - name: TZ
    value: "America/Chicago"

resources:
  requests:
    memory: 128Mi
    cpu: 50m
  limits:
    memory: 512Mi
    cpu: 200m

# Remove persistence section for now to test
# persistence:
#   logs:
#     enabled: true
#     type: emptyDir
#     mountPath: /app/config/logs