---
image:
  repository: ghcr.io/gethomepage/homepage
  tag: v0.8.8

enableRbac: false

service:
  main:
    ports:
      http:
        port: 3000

ingress:
  main:
    enabled: true
    labels:
      # This label will enable discover of this deployment in Homepage
      gethomepage.dev/enabled: "true"
    annotations:
      # These annotations will configure how this deployment is shown in Homepage
      gethomepage.dev/name: "Homepage"
      gethomepage.dev/description: "A modern, secure, highly customizable application dashboard."
      gethomepage.dev/group: "A New Group"
      gethomepage.dev/icon: "homepage.png"
    ingressClassName: "nginx"
    hosts:
      - host: "homepage.local"
        paths:
          - path: /
            pathType: Prefix
    # tls:
    #   - hosts:
    #       - *host


env:
  - name: HOMEPAGE_ALLOWED_HOSTS
    value: "home.homelab,localhost"
  - name: TZ
    value: "America/Chicago"

resources:
  requests:
    memory: 128Mi
    cpu: 50m
  limits:
    memory: 512Mi
    cpu: 200m


persistence:
  logs:
    enabled: true
    type: emptyDir
    mountPath: /app/config/logs