config:
  useExistingConfigMap: "homepage-config"

ingress:
  main:
    enabled: true
    ingressClassName: nginx
    hosts:
      - host: home.homelab
        paths:
          - path: /
            pathType: Prefix

enableRbac: false