---
image:
  repository: ghcr.io/gethomepage/homepage
  pullPolicy: IfNotPresent
  # tag: v0.6.0

enableRbac: false

serviceAccount:
  name: ""
  create: false

service:
  main:
    ports:
      http:
        port: 3000

controller:
  strategy: RollingUpdate
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 25%

ingress:
  main:
    enabled: true
    labels:
      gethomepage.dev/enabled: "true"
    annotations:
      gethomepage.dev/name: "Homepage"
      gethomepage.dev/description: "A modern, secure, highly customizable application dashboard."
      gethomepage.dev/group: "Dashboards"
      gethomepage.dev/icon: "homepage.png"
      # Add cert-manager annotation
      cert-manager.io/cluster-issuer: "selfsigned-issuer"
    ingressClassName: nginx
    hosts:
      - host: home.homelab
        paths:
          - path: /
            pathType: Prefix
    # Add TLS configuration
    tls:
      - hosts:
          - home.homelab
        secretName: homepage-tls

# Homepage configuration files
config:
  # Settings configuration
  settings:
    title: "K3s Homelab"
    theme: dark
    color: blue
    headerStyle: boxed
    language: en
    layout:
      Smart Home:
        icon: home
        columns: 2
      Kubernetes:
        icon: kubernetes
        columns: 3
      Monitoring:
        icon: grafana
        columns: 2
    quicklaunch:
      searchDescriptions: true
      showSearchSuggestions: true
      provider: duckduckgo

  # Bookmarks configuration  
  bookmarks:
    - Development:
        - GitHub:
            - abbr: GH
              href: https://github.com/
        - Kubernetes Docs:
            - abbr: K8S
              href: https://kubernetes.io/docs/home/
        - ArgoCD Docs:
            - abbr: ARGO
              href: https://argo-cd.readthedocs.io/
    - Tools:
        - ChatGPT:
            - abbr: GPT
              href: https://chat.openai.com/
        - Weather:
            - abbr: WX
              href: https://weather.gov/

  # Services configuration
  services:
    - Smart Home:
        - Home Assistant:
            href: https://homeassistant.homelab
            description: "Home automation hub"
            icon: home-assistant.png
            status: https://homeassistant.homelab
  
        - OctoPrint:
            href: https://octoprint.homelab
            description: "3D Printer Control"
            icon: octoprint.png

    - Kubernetes Infrastructure:
        - ArgoCD:
            href: https://argocd.homelab
            description: "GitOps CD for Kubernetes"
            icon: argocd.png
            status: https://argocd.homelab/healthz

        - Longhorn:
            href: https://longhorn.homelab
            description: "Cloud native storage"
            icon: longhorn.png
            status: https://longhorn.homelab

        - Cert Manager:
            href: https://cert-manager.io/docs/
            description: "Certificate management"
            icon: cert-manager.png
            
        - MetalLB:
            href: https://metallb.io/
            description: "Load balancer for bare metal"
            icon: metallb.png
            
    - Monitoring:
        - Grafana:
            href: https://grafana.homelab
            description: "Metrics visualization"
            icon: grafana.png

        - Prometheus:
            href: https://prometheus.homelab
            description: "Metrics collection"
            icon: prometheus.png

        - Loki:
            href: https://loki.homelab
            description: "Log aggregation"
            icon: loki.png
            
  # Widgets configuration
  widgets:
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        disk: true
    - search:
        provider: duckduckgo
        target: _blank
    - datetime:
        format:
          timeStyle: short
          dateStyle: full
        locale: en-US
    - kubernetes:
        cluster: k3s
        namespace: true
        label: true
        show_all: true

# Environment variables
env:
  - name: HOMEPAGE_ALLOWED_HOSTS
    value: "home.homelab,localhost"
  - name: TZ
    value: "America/Chicago"  # Set to your timezone

persistence:
  config:
    enabled: true
    type: pvc
    storageClass: "longhorn"
    accessMode: ReadWriteOnce
    size: 1Gi
    mountPath: "/app/config"
  logs:
    enabled: true
    type: emptyDir
    mountPath: "/app/config/logs"

resources:
  requests:
    memory: "64Mi"
    cpu: "25m"
  limits:
    memory: "256Mi"
    cpu: "100m"