---
controller:
  service:
    type: LoadBalancer
    loadBalancerIP: 192.168.4.20

  ingressClassResource:
    default: true
    name: nginx
    
  extraArgs:
    default-ssl-certificate: "cert-manager/wildcard-homelab-tls"
  
  config:
    ssl-redirect: "true"
    force-ssl-redirect: "true"