# Minimal Loki configuration for homelab with filesystem storage
loki:
  auth_enabled: false
  schemaConfig:
    configs:
      - from: "2020-10-24"
        store: boltdb-shipper
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 24h

# Set deployment mode
deploymentMode: SingleBinary

# Single binary configuration
singleBinary:
  replicas: 1
  persistence:
    enabled: true
    size: 5Gi
    storageClassName: longhorn

# Critical fix: Define storage configuration with bucket names
# even though we're using filesystem storage
storage:
  type: filesystem
  bucketNames:
    chunks: loki-chunks
    ruler: loki-ruler
    admin: loki-admin

# Disable gateway since we don't need ingress
gateway:
  enabled: false

# Disable tests to avoid validation errors
test:
  enabled: false

# Disable unnecessary monitoring components
monitoring:
  enabled: false

# Resource limits appropriate for Raspberry Pi
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi