# Simplified Loki values for homelab
service:
  enabled: true

persistence:
  enabled: true
  storageClassName: longhorn
  size: 10Gi

serviceMonitor:
  enabled: true

ingress:
  enabled: false
  ingressClassName: nginx
  hosts:
    - loki.homelab
  paths:
    - /

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi