loki:
  enabled: true
  persistence:
    enabled: true
    size: 10Gi
    storageClassName: longhorn
    mountPath: /data/loki  # Changed from default /var/loki which is read-only
  config:
    auth_enabled: false
    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h
    storage_config:
      boltdb_shipper:
        active_index_directory: /data/loki/index  
        cache_location: /data/loki/index_cache    
        cache_ttl: 24h
        shared_store: filesystem
      filesystem:
        directory: /data/loki/chunks
    
    # Add log retention
    limits_config:
      retention_period: 720h  # 30 days
    
    # Fix memberlist configuration for single instance
    common:
      ring:
        kvstore:
          store: inmemory
  
  # Resource limits for stable operation
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi