# Single Binary configuration for Loki on Raspberry Pi
loki:
  auth_enabled: false
  schemaConfig:
    configs:
      - from: "2020-10-24"
        store: boltdb-shipper
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 24h

# Explicitly set deployment mode
deploymentMode: SingleBinary

# Configure single binary mode ONLY (disable SimpleScalable components)
singleBinary:
  replicas: 1
  persistence:
    enabled: true
    size: 5Gi
    storageClassName: longhorn

# Disable all SimpleScalable components
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

# Disable gateway since we don't need ingress
gateway:
  enabled: false

# Disable tests to avoid validation errors
test:
  enabled: false

# Disable monitoring components
monitoring:
  selfMonitoring:
    enabled: false
  lokiCanary:
    enabled: false
  grafanaAgent:
    enabled: false

# Resource limits appropriate for Raspberry Pi
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi