# Simplified Loki configuration without ingress
loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem

# Use single binary mode (best for Raspberry Pi)
deploymentMode: SingleBinary
singleBinary:
  replicas: 1
  persistence:
    enabled: true
    size: 5Gi
    storageClassName: longhorn

# Disable gateway since we don't need ingress
gateway:
  enabled: false

# Disable tests to avoid validation errors
test:
  enabled: false

# Disable monitoring components
monitoring:
  selfMonitoring:
    enabled: false
  lokiCanary:
    enabled: false
  grafanaAgent:
    enabled: false

# Resource limits appropriate for Raspberry Pi
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi