# Values for loki-stack for homelab with correct storage paths
loki:
  enabled: true
  persistence:
    enabled: true
    size: 10Gi
    storageClassName: longhorn
    mountPath: /data/loki  # Changed from default /var/loki which is read-only
  config:
    auth_enabled: false
    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h
    storage_config:
      boltdb_shipper:
        active_index_directory: /data/loki/index  
        cache_location: /data/loki/index_cache    
        cache_ttl: 24h
        shared_store: filesystem
      filesystem:
        directory: /data/loki/chunks            


promtail:
  enabled: false


grafana:
  enabled: false


fluent-bit:
  enabled: false
prometheus:
  enabled: false