# Values for loki-stack for homelab
loki:
  enabled: true
  persistence:
    enabled: true
    size: 10Gi
    storageClassName: longhorn
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  config:
    auth_enabled: false
    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h
    storage_config:
      boltdb_shipper:
        active_index_directory: /var/loki/index
        cache_location: /var/loki/index_cache
        cache_ttl: 24h
        shared_store: filesystem
      filesystem:
        directory: /var/loki/chunks

# Disable promtail 
promtail:
  enabled: false


grafana:
  enabled: false

# Disable other components we don't need
fluent-bit:
  enabled: false
prometheus:
  enabled: false