# Custom values for Loki Helm chart
loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
  persistence:
    enabled: true
    size: 10Gi
    storageClassName: longhorn

# Disable tests
test:
  enabled: false

# Fully disable monitoring components
monitoring:
  enabled: false
  selfMonitoring:
    enabled: false
  lokiCanary:
    enabled: false
  grafanaAgent:
    enabled: false

# Disable CRDs completely
crds:
  enabled: false
  create: false

gateway:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - host: loki.homelab
        paths:
          - path: /
            pathType: Prefix

# Single binary mode for small deployments
singleBinary:
  enabled: true
  replicas: 1
  persistence:
    enabled: true
    size: 10Gi
    storageClassName: longhorn