---
preUpgradeChecker:
  jobEnabled: false

persistence:
  defaultClass: true
  defaultClassReplicaCount: 1

defaultSettings:
  defaultReplicaCount: 1

# Optimize CSI components for 2-node cluster
csi:
  attacher:
    replicaCount: 2
  provisioner:
    replicaCount: 2
  resizer:
    replicaCount: 2
  snapshotter:
    replicaCount: 2

# Reduce UI replicas
longhornUI:
  replicas: 1

# This is the ingress configuration from the original application
ingress:
  enabled: true
  host: longhorn.opsguy.io
  path: /
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  ingressClassName: nginx
  tls: true
  tlsSecret: wildcard-opsguy-io-tls

# This is the additional ingress configuration from manifests/longhorn/ingress.yaml
additionalIngress:
  enabled: true
  name: longhorn-ui
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/rewrite-target: /
  host: home.opsguy.io
  path: /longhorn
  pathType: Prefix
  serviceName: longhorn-frontend
  servicePort: 80