controller:
  enabled: true
speaker:
  enabled: true
<<<<<<< HEAD
=======

# Custom resources from manifests/metallb/config.yaml
crds:
  enabled: true
  
# These will be created as additional resources
additionalManifests:
  - apiVersion: metallb.io/v1beta1
    kind: IPAddressPool
    metadata:
      name: default-pool
      namespace: metallb-system
    spec:
      addresses:
        - 192.168.4.20-192.168.4.30
  
  - apiVersion: metallb.io/v1beta1
    kind: L2Advertisement
    metadata:
      name: default
      namespace: metallb-system
    spec: {}
>>>>>>> fc229cb68d1b51844fb6c54acc1acb815989a322
