# Simplified values for Prometheus Helm chart
alertmanager:
  enabled: true
  persistence:
    enabled: true
    storageClassName: longhorn
    size: 2Gi
  ingress:
    enabled: false
    ingressClassName: nginx
<<<<<<< HEAD
    pathType: Prefix
    hosts: 
=======
    hosts:
>>>>>>> fc229cb68d1b51844fb6c54acc1acb815989a322
      - alertmanager.homelab

server:
  retention: 15d
  persistentVolume:
    enabled: true
    storageClassName: longhorn
    size: 10Gi
  ingress:
    enabled: false
    ingressClassName: nginx
    pathType: Prefix
    hosts:
      - prometheus.homelab
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi

pushgateway:
  enabled: true

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true

serviceMonitorSelectorNilUsesHelmValues: false
serviceMonitorSelector: {}
serviceMonitorNamespaceSelector: {}

# Configure scrape configs for common services
additionalScrapeConfigs:
  - job_name: 'kubernetes-nodes-cadvisor'
    scrape_interval: 10s
    scrape_timeout: 10s
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecure_skip_verify: true
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    kubernetes_sd_configs:
      - role: node
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - target_label: __address__
        replacement: kubernetes.default.svc:443
      - source_labels: [__meta_kubernetes_node_name]
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor