# Configuration for the Promtail Helm chart
config:
  # Client configuration for sending logs to Loki
  clients:
    - url: http://loki-stack.monitoring.svc.cluster.local:3100/loki/api/v1/push
  
  # Define scrape configurations and processing pipeline
  snippets:
    extraScrapeConfigs: |
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        pipeline_stages:
          - docker: {}
          - json: {}
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: 
              - __meta_kubernetes_namespace
            target_label: namespace
          - source_labels:
              - __meta_kubernetes_pod_name
            target_label: pod
          - source_labels:
              - __meta_kubernetes_pod_container_name
            target_label: container
          - source_labels:
              - __meta_kubernetes_pod_node_name
            target_label: node

# Run as a DaemonSet to collect logs from all nodes
daemonset:
  enabled: true

# Allow Promtail to run on control plane nodes
tolerations:
- key: node-role.kubernetes.io/control-plane
  operator: Exists
  effect: NoSchedule
- key: node-role.kubernetes.io/master
  operator: Exists
  effect: NoSchedule

# Explicitly define volumes to ensure access to logs
volumeMounts:
  - name: run
    mountPath: /run/promtail
  - name: varlog
    mountPath: /var/log
  - name: varlibdockercontainers
    mountPath: /var/lib/docker/containers
    readOnly: true
  - name: positions
    mountPath: /positions

volumes:
  - name: run
    hostPath:
      path: /run/promtail
  - name: varlog
    hostPath:
      path: /var/log
  - name: varlibdockercontainers
    hostPath:
      path: /var/lib/docker/containers
  - name: positions
    hostPath:
      path: /var/lib/promtail/positions

# Configure positions file to track the logs that have been read
args:
  - -config.file=/etc/promtail/promtail.yaml
  - -positions.file=/positions/positions.yaml

# Set resource limits appropriate for Raspberry Pi
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

# Enable service monitoring for Prometheus
serviceMonitor:
  enabled: true

# Set security context to allow reading logs
securityContext:
  readOnlyRootFilesystem: true
  runAsGroup: 0
  runAsUser: 0  # Run as root to ensure access to all log files

# Set priority class to ensure Promtail starts early
priorityClassName: system-node-critical