apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-settings
  namespace: homepage
data:
  settings.yaml: |
    title: "K3s Homelab"
    theme: dark
    color: blue
    headerStyle: boxed
    language: en
    layout:
      Smart Home:
        icon: home
        columns: 2
      Kubernetes:
        icon: kubernetes
        columns: 3
      Monitoring:
        icon: grafana
        columns: 2
    quicklaunch:
      searchDescriptions: true
      showSearchSuggestions: true
      provider: duckduckgo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-services
  namespace: homepage
data:
  services.yaml: |
    - Smart Home:
        - Home Assistant:
            href: https://homeassistant.homelab
            description: "Home automation hub"
            icon: home-assistant.png
            status: https://homeassistant.homelab
    
        - OctoPrint:
            href: https://octoprint.homelab
            description: "3D Printer Control"
            icon: octoprint.png

    - Kubernetes Infrastructure:
        - ArgoCD:
            href: https://argocd.homelab
            description: "GitOps CD for Kubernetes"
            icon: argocd.png
            status: https://argocd.homelab/healthz

        - Longhorn:
            href: https://longhorn.homelab
            description: "Cloud native storage"
            icon: longhorn.png
            status: https://longhorn.homelab

        - Cert Manager:
            href: https://cert-manager.io/docs/
            description: "Certificate management"
            icon: cert-manager.png
            
        - MetalLB:
            href: https://metallb.io/
            description: "Load balancer for bare metal"
            icon: metallb.png
            
    - Monitoring:
        - Grafana:
            href: https://grafana.homelab
            description: "Metrics visualization"
            icon: grafana.png

        - Prometheus:
            href: https://prometheus.homelab
            description: "Metrics collection"
            icon: prometheus.png

        - Loki:
            href: https://loki.homelab
            description: "Log aggregation"
            icon: loki.png
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-widgets
  namespace: homepage
data:
  widgets.yaml: |
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        disk: true
    - search:
        provider: duckduckgo
        target: _blank
    - datetime:
        format:
          timeStyle: short
          dateStyle: full
        locale: en-US
    - kubernetes:
        cluster: k3s
        namespace: true
        label: true
        show_all: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-bookmarks
  namespace: homepage
data:
  bookmarks.yaml: |
    - Development:
        - GitHub:
            - abbr: GH
              href: https://github.com/
        - Kubernetes Docs:
            - abbr: K8S
              href: https://kubernetes.io/docs/home/
        - ArgoCD Docs:
            - abbr: ARGO
              href: https://argo-cd.readthedocs.io/
    - Tools:
        - ChatGPT:
            - abbr: GPT
              href: https://chat.openai.com/
        - Weather:
            - abbr: WX
              href: https://weather.gov/
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-kubernetes
  namespace: homepage
data:
  kubernetes.yaml: |
    mode: cluster