apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applicationsets
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: https://github.com/BrandonCantrell/homelab.git
    targetRevision: helm-refactor
    path: k3s-cluster/kube-apps/applicationsets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true