apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-config
  namespace: argocd
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/BrandonCantrell/homelab.git
    targetRevision: HEAD
    path: k3s-cluster/kube-apps/manifests/argocd
    directory:
      recurse: true
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
