apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: default
  destination:
    namespace: metallb-system
    server: https://kubernetes.default.svc
  source:
    repoURL: https://metallb.github.io/metallb
    chart: metallb
    targetRevision: 0.14.6
    helm:
      valueFiles:
        - ../manifests/metallb/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
