apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-volv-pvc-stuff
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 260Gi
