apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homeassistant
  namespace: argocd
spec:
  project: default
  destination:
    namespace: homeassistant
    server: https://kubernetes.default.svc
  source:
    repoURL: http://pajikos.github.io/home-assistant-helm-chart
    chart: home-assistant
    targetRevision: 0.2.117
    helm:
      values: |
        persistence:
          enabled: true
          accessMode: ReadWriteOnce
          size: 5Gi
          storageClass: "longhorn"

        homeassistant:
          externalUrl: "http://homeassistant.homelab"
          configuration: |
            http:
              use_x_forwarded_for: true
              trusted_proxies:
                - 10.42.0.0/16
                - 192.168.4.0/24
                - 127.0.0.1
                - 10.43.0.0/16  # Add this to include cluster IPs like the service itself



        service:
          enabled: true
          type: ClusterIP
          port: 8123

        ingress:
          enabled: true
          external: false
          className: nginx
          annotations:
            kubernetes.io/ingress.class: nginx
            nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
            nginx.ingress.kubernetes.io/rewrite-target: /
          hosts:
            - host: homeassistant.homelab
              paths:
                - path: /
                  pathType: ImplementationSpecific
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
