apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homeassistant
  namespace: argocd
spec:
  project: default
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: http://pajikos.github.io/home-assistant-helm-chart
    chart: home-assistant
    targetRevision: 0.2.117
    helm:
      values: |
        persistence:
          enabled: true
          accessMode: ReadWriteOnce
          size: 5Gi
          storageClass: "longhorn"

        homeAssistant:
          externalUrl: "http://homeassistant.homelab"

        ingress:
          enabled: true
          className: nginx
          annotations:
            kubernetes.io/ingress.class: nginx
            nginx.ingress.kubernetes.io/backend-protocol: "http"
          hosts:
            - host: homeassistant.homelab
              paths:
                - path: /
                  pathType: Prefix

              

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
