#{{- printf "DEBUG: ingress.enabled = %v\n" .Values.ingress.enabled | quote }}

{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "stash.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "stash.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
