replicaCount: 1

ingress:
  enabled: false

controller:
  service:
    type: LoadBalancer
    # loadBalancerIP: 192.168.4.20
    annotations:
      homelab.sync: "force"

image:
  repository: nginx
  tag: "1.21"
  pullPolicy: IfNotPresent
