---
- name: Update apt packages
  apt:
    update_cache: true
    upgrade: dist

- name: Install essential packages
  apt:
    name:
      - curl
      - git
      - nfs-common
      - iptables
      - python3-pip
      - net-tools
    state: present

- name: Ensure cgroup settings in /boot/firmware/cmdline.txt
  lineinfile:
    path: /boot/firmware/cmdline.txt
    regexp: '^(.*)$'
    line: '\1 cgroup_memory=1 cgroup_enable=memory cgroup_enable=cpuset'
    backrefs: yes
  notify: Reboot if required

- name: Disable swap now
  command: swapoff -a
  when: ansible_swaptotal_mb > 0
  ignore_errors: true

- name: Disable swap permanently in /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*\sswap\s)'
    replace: '# \1'
  ignore_errors: true

- name: Disable dphys-swapfile service if present
  systemd:
    name: dphys-swapfile
    enabled: false
    state: stopped
  ignore_errors: true

- name: Set hostname based on inventory hostname
  hostname:
    name: "{{ inventory_hostname }}"
