---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mqtt-opsguy-io-tls
  namespace: mosquitto
spec:
  secretName: opsguy-io-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - mqtt.opsguy.io