---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: mosquitto
  labels:
    app.kubernetes.io/name: mosquitto
data:
  mosquitto.conf: |
    # Mosquitto MQTT Broker Configuration
    
    # Basic settings
    user mosquitto
    
    # Listeners
    listener 1883
    protocol mqtt
    
    listener 9001
    protocol websockets
    
    # Persistence
    persistence true
    persistence_location /mosquitto/data/
    
    # Logging
    log_dest stdout
    log_type error
    log_type warning
    log_type notice
    log_type information
    log_timestamp true
    
    # Security - allow anonymous for now (can be configured later)
    allow_anonymous true
    
    # Maximum connections
    max_connections -1
    
    # Retain messages
    retain_available true
    
    # Message size limits
    message_size_limit 268435456
    
    # Connection settings  
    keepalive_interval 60
    max_keepalive 65535