---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: alertmanager
  namespace: monitoring-servicemonitors
  labels:
    app.kubernetes.io/name: alertmanager
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    port: http
    scheme: http
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/name: alertmanager
      app.kubernetes.io/instance: prometheus