# Home Assistant ServiceMonitor
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: home-assistant
  namespace: monitoring-servicemonitors
  labels:
    app.kubernetes.io/name: home-assistant
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ha
  namespaceSelector:
    matchNames:
    - homeassistant
  endpoints:
  - port: http
    interval: 60s
    path: /api/prometheus
    # Note: Requires Long-Lived Access Token configured in Home Assistant
---
# Homebridge ServiceMonitor (HTTP probe style)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: homebridge
  namespace: monitoring-servicemonitors
  labels:
    app.kubernetes.io/name: homebridge
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: homebridge
  namespaceSelector:
    matchNames:
    - homebridge
  endpoints:
  - port: http
    interval: 60s
    path: /
    # Basic HTTP health check
---
# Homepage ServiceMonitor
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: homepage
  namespace: monitoring-servicemonitors
  labels:
    app.kubernetes.io/name: homepage
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: homepage
  namespaceSelector:
    matchNames:
    - homepage
  endpoints:
  - port: http
    interval: 60s
    path: /api/healthcheck
---
# Mosquitto ServiceMonitor
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mosquitto
  namespace: monitoring-servicemonitors
  labels:
    app.kubernetes.io/name: mosquitto
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mosquitto
  namespaceSelector:
    matchNames:
    - mosquitto
  endpoints:
  - port: mqtt
    interval: 60s
    path: /metrics