---
- name: Deploy K3s cluster
  hosts: k3s_cluster
  become: true
  vars:
    k3s_become: true
    k3s_version: v1.29.4+k3s1
    k3s_control_node: "{{ hostvars[inventory_hostname].k3s_control_node | default(false) }}"
  roles:
    - role: xanmanning.k3s
