apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnsmasq
  labels:
    app: dnsmasq
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: dnsmasq
  template:
    metadata:
      labels:
        app: dnsmasq
    spec:
      containers:
        - name: dnsmasq
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: DNSMASQ_ADDRESSES
              value: |
                {{- range .Values.dnsmasq.domainMappings }}
                /{{ .domain }}/{{ .ip }}
                {{- end }}
          command:
            - /bin/sh
            - -c
            - |
              echo "${DNSMASQ_ADDRESSES}" | xargs -n1 echo address= > /etc/dnsmasq.d/custom.conf && \
              dnsmasq -k --log-facility=-
          ports:
            - containerPort: 53
              protocol: UDP
