apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnsmasq
  labels:
    app: dnsmasq
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: dnsmasq
  template:
    metadata:
      labels:
        app: dnsmasq
    spec:
      containers:
        - name: dnsmasq
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args:
            {{- range .Values.dnsmasq.domainMappings }}
            - "--address=/{{ .domain }}/{{ .ip }}"
            {{- end }}
          ports:
            - containerPort: 53
              protocol: UDP
