apiVersion: v1
kind: Service
metadata:
  name: dnsmasq
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  ports:
    - name: dns
      port: 53
      protocol: UDP
      targetPort: 53
  selector:
    app: dnsmasq
