apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
spec:
  project: default
  destination:
    namespace: homepage
    server: https://kubernetes.default.svc
  source:
    repoURL: https://jameswynn.github.io/helm-charts
    chart: homepage
    targetRevision: 2.0.2
    helm:
      values: |
        image:
          repository: ghcr.io/gethomepage/homepage
          # tag: v0.6.0
        
        enableRbac: false
        
        serviceAccount:
          name: ""
          create: false
        
        service:
          main:
            ports:
              http:
                port: 3000
        
        controller:
          strategy: RollingUpdate
          rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
        
        ingress:
          main:
            enabled: true
            labels:
              gethomepage.dev/enabled: "true"
            annotations:
              gethomepage.dev/name: "Homepage"
              gethomepage.dev/description: "A modern, secure, highly customizable application dashboard."
              gethomepage.dev/group: "A New Group"
              gethomepage.dev/icon: "homepage.png"
            ingressClassName: nginx
            hosts:
              - host: home.homelab
                paths:
                  - path: /
                    pathType: Prefix
            tls: []
        
        config:
          bookmarks:
            - Developer:
                - Github:
                    - abbr: GH
                      href: https://github.com/
          
          services:
            - Smart Home Services:
                - Home Assistant:
                    href: http://homeassistant.homelab
                    description: "HA"
          
                - WLED Nanoleaf Tree:
                    href: http://wled-tree.homelab
                    description: "Tree"
  
                - OctoPrint:
                    href: http://octoprint.homelab
                    description: "OctoPrint"


            - Homelab Resources:
                - Longhorn UI:
                    href: http://longhorn.homelab
                    description: "Homepage is the best"

                - ArgoCD:
                    href: https://192.168.4.10:30080
                    description: "ArgoCD"
            
            - My Third Group:
                - My Third Service:
                    href: http://localhost/
                    description: "Homepage is 😎"
          
          widgets:
            - resources:
                backend: resources
                expanded: true
                cpu: true
                memory: true
            - search:
                provider: duckduckgo
                target: _blank
          
          kubernetes:
            mode: disable
          
          settings: {}
          
          settingsString: |
            title: Homepage
            headerStyle: boxed
            layout:
              My First Group:
              My Second Group:
              My Third Group:
        
        env:
          - name: HOMEPAGE_ALLOWED_HOSTS
            value: "home.homelab"
        
        persistence:
          logs:
            enabled: true
            type: emptyDir
            mountPath: "/app/config/logs"
        
        resources:
          requests:
            memory: "10Mi"
            cpu: "10m"
          limits:
            memory: "200Mi"
            cpu: "500m"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
