apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
spec:
  project: default
  destination:
    namespace: homepage
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://jameswynn.github.io/helm-charts
      chart: homepage
      targetRevision: 2.0.2            
      path: .                          
      helm:
        valueFiles:
          - $values/k3s-cluster/kube-apps/homepage/values.yaml
    - repoURL: https://github.com/BrandonCantrell/homelab.git  
      targetRevision: main
      ref: values  # Maps to $values variable
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
