---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
        - ArgoCD:
            - abbr: ARGO
              href: http://192.168.4.10:30080
        - Kubernetes Docs:
            - abbr: K8S
              href: https://kubernetes.io/docs/home/

  services.yaml: |
    - Infrastructure:
        - ArgoCD:
            href: http://192.168.4.10:30080
            description: GitOps CD for Kubernetes
            icon: argocd.png
        - Longhorn:
            href: http://longhorn.homelab
            description: Distributed storage
            icon: longhorn.png
        - Grafana:
            href: http://grafana.homelab
            description: Metrics visualization
            icon: grafana.png
        - Prometheus:
            href: http://prometheus.homelab
            description: Metrics collection
            icon: prometheus.png

  widgets.yaml: |
    - resources:
        backend: kubernetes
        expanded: true
        cpu: true
        memory: true
    - search:
        provider: duckduckgo
        target: _blank


  kubernetes.yaml: ""

  docker.yaml: ""

  settings.yaml: |
    title: K3s Homelab Dashboard
    headerStyle: boxed
    theme: dark
    color: blue
    layout:
      Infrastructure:
        style: row
        columns: 4