---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
        - ArgoCD:
            - abbr: ARGO
              href: http://192.168.4.10:30080
        - Kubernetes Docs:
            - abbr: K8S
              href: https://kubernetes.io/docs/home/

  services.yaml: |
    - Infrastructure:
        - ArgoCD:
            href: http://192.168.4.10:30080
            description: GitOps CD for Kubernetes
            icon: argocd.png
        - Longhorn:
            href: http://longhorn.homelab
            description: Distributed storage
            icon: longhorn.png
            
    - Monitoring:
        - Grafana:
            href: http://grafana.homelab
            description: Metrics visualization
            icon: grafana.png
        - Prometheus:
            href: http://prometheus.homelab
            description: Metrics collection
            icon: prometheus.png
            
    - Home Apps:
        - WLED Nanoleaf Tree:
            href: http://wled-tree.homelab
            description: Nanoleaf Tree
            icon: wled.png
        - Home Assistant:
            href: https://homeassistant.homelab
            description: Home Assistant
            icon: home-assistant.png
        - Octoprint:
            href: https://octoprint.homelab
            description: Octoprint
            icon: octoprint.png
        - Homebridge:
            href: http://homebridge.homelab
            description: HomeKit bridge
            icon: homebridge.png

  widgets.yaml: |
    - resources:
        backend: resources
        expanded: false
        cpu: true
        memory: true
    - search:
        provider: duckduckgo
        target: _blank
    - datetime:
        text_size: xl
        format:
          timeStyle: short
          dateStyle: short

  kubernetes.yaml: |
    mode: disable

  docker.yaml: ""

  settings.yaml: |
    title: K3s Homelab Dashboard
    headerStyle: boxed
    theme: dark
    color: blue
    target: _self
    
    # Background image configuration
    background: https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=2560&q=80
    backgroundOpacity: 15
    backgroundFilter: 
      blur: 0
      saturation: 100
      brightness: 100
    
    # Layout configuration for clean columns
    layout:
      Infrastructure:
        style: column
        icon: mdi-server-network
        columns: 2
      Monitoring: 
        style: column
        icon: mdi-chart-line
        columns: 2
      Home Apps:
        style: column
        icon: mdi-home-automation
        columns: 3
        
    # Performance optimizations
    hideErrors: true
    hideVersion: false
    fiveColumns: false
    statusStyle: "dot"
    
    # Quick launch settings
    quicklaunch:
      searchDescriptions: false
      hideInternetSearch: false
      hideVisitURL: false
      provider: duckduckgo