---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: homepage
  labels:
    app: homepage
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
      annotations:
        # Force pod restart when ConfigMap changes - update this hash when you change the ConfigMap
        configmap/hash: "homepage-config-v3"
    spec:
      serviceAccountName: homepage
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: homepage
        image: ghcr.io/gethomepage/homepage:v1.4.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        env:
        - name: HOMEPAGE_CONFIG_DIR
          value: /app/config
        - name: HOMEPAGE_CACHE_DIR
          value: /cache
        - name: HOMEPAGE_LOGS_DIR
          value: /logs
        - name: LOG_LEVEL
          value: info
        - name: HOMEPAGE_VAR_TITLE
          value: "K3s Homelab Dashboard"
        # Required for v1.0.0+ security
        - name: HOMEPAGE_ALLOWED_HOSTS
          value: "home.opsguy.io,localhost,127.0.0.1"
        # Performance optimizations
        - name: HOMEPAGE_FILE_WATCHER
          value: "false"
        - name: HOMEPAGE_DISABLE_LOGGING
          value: "false"
        - name: DISABLE_FILE_WATCHER
          value: "true"
        volumeMounts:
        - name: config
          mountPath: /app/config
          readOnly: true
        - name: cache
          mountPath: /cache
        - name: logs
          mountPath: /logs
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
          limits:
            memory: 512Mi
            cpu: 500m
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
      volumes:
      - name: config
        configMap:
          name: homepage-config
      - name: cache
        emptyDir:
          sizeLimit: 100Mi
      - name: logs
        emptyDir:
          sizeLimit: 100Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30