apiVersion: metallb.io/v1beta1
kind: AddressPool
metadata:
  name: default-pool
  namespace: metallb-system
spec:
  protocol: layer2
  addresses:
    - 192.168.4.20-192.168.4.30

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
  namespace: metallb-system
spec: {}
