apiVersion: v1
kind: ServiceAccount
metadata:
  name: metallb-controller
  namespace: metallb-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metallb-controller
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints", "nodes", "pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metallb.io"]
    resources: ["ipaddresspools", "l2advertisements"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metallb-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metallb-controller
subjects:
  - kind: ServiceAccount
    name: metallb-controller
    namespace: metallb-system
