---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: charts-applications
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: stash
        namespace: stash
        path: k3s-cluster/kube-apps/charts/stash
  template:
    metadata:
      name: '{{name}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/BrandonCantrell/homelab.git
        targetRevision: helm-refactor
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true