---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-helm-applications
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: cert-manager
        namespace: cert-manager
        path: k3s-cluster/kube-apps/charts/cert-manager
        valuesPath: ../../values/cert-manager-values.yaml
      - name: loki-stack
        namespace: monitoring
        path: k3s-cluster/kube-apps/charts/loki-stack
        valuesPath: ../../values/loki-stack-values.yaml
      - name: grafana
        namespace: monitoring
        path: k3s-cluster/kube-apps/charts/grafana
        valuesPath: ../../values/grafana-values.yaml
      - name: prometheus
        namespace: monitoring
        path: k3s-cluster/kube-apps/charts/prometheus
        valuesPath: ../../values/prometheus-values.yaml
      - name: ingress-nginx
        namespace: ingress-nginx
        path: k3s-cluster/kube-apps/charts/ingress-nginx
        valuesPath: ../../values/ingress-nginx-values.yaml
      - name: longhorn
        namespace: longhorn-system
        path: k3s-cluster/kube-apps/charts/longhorn
        valuesPath: ../../values/longhorn-values.yaml
      - name: metallb-app
        namespace: metallb-system
        path: k3s-cluster/kube-apps/charts/metallb
        valuesPath: ../../values/metallb-values.yaml
      # - name: homepage
      #   namespace: homepage
      #   path: k3s-cluster/kube-apps/charts/homepage
      #   valuesPath: ../../values/homepage-values.yaml
      - name: homeassistant
        namespace: homeassistant
        path: k3s-cluster/kube-apps/charts/home-assistant
        valuesPath: ../../values/homeassistant-values.yaml
      - name: promtail
        namespace: monitoring
        path: k3s-cluster/kube-apps/charts/promtail
        valuesPath: ../../values/promtail-values.yaml
  template:
    metadata:
      name: '{{name}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/BrandonCantrell/homelab.git
        targetRevision: develop
        path: '{{path}}'
        helm:
          releaseName: '{{name}}'
          valueFiles:
          - '{{valuesPath}}'
          - '{{valuesPath}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true