apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-helm-applications
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      # - name: cert-manager
      #   namespace: cert-manager
      #   chart: cert-manager
      #   repo: https://charts.jetstack.io
      #   version: v1.13.2
      #   valuesPath: k3s-cluster/kube-apps/values/cert-manager-values.yaml
      # - name: loki
      #   namespace: monitoring
      #   chart: loki
      #   repo: https://grafana.github.io/helm-charts
      #   version: 5.8.11
      #   valuesPath: k3s-cluster/kube-apps/values/loki-values.yaml
      # - name: grafana
      #   namespace: monitoring
      #   chart: grafana
      #   repo: https://grafana.github.io/helm-charts
      #   version: 6.58.8
      #   valuesPath: k3s-cluster/kube-apps/values/grafana-values.yaml
      # - name: prometheus
      #   namespace: monitoring
      #   chart: prometheus
      #   repo: https://prometheus-community.github.io/helm-charts
      #   version: 22.6.7
      #   valuesPath: k3s-cluster/kube-apps/values/prometheus-values.yaml
      - name: ingress-nginx
        namespace: argocd
        chart: ingress-nginx
        repo: https://kubernetes.github.io/ingress-nginx
        version: 4.12.1
        valuesPath: k3s-cluster/kube-apps/values/ingress-nginx-values.yaml
      - name: longhorn
        namespace: longhorn-system
        chart: longhorn
        repo: https://charts.longhorn.io
        version: 1.8.1
        valuesPath: k3s-cluster/kube-apps/values/longhorn-values.yaml
      - name: metallb-app
        namespace: metallb-system
        chart: metallb
        repo: https://metallb.github.io/metallb
        version: 0.14.6
        valuesPath: k3s-cluster/kube-apps/values/metallb-values.yaml
      - name: homepage
        namespace: homepage
        chart: homepage-app
        repo: https://jameswynn.github.io/helm-charts
        version: 2.0.2
        valuesPath: k3s-cluster/kube-apps/values/homepage-values.yaml
      - name: homeassistant
        namespace: homeassistant
        chart: home-assistant
        repo: http://pajikos.github.io/home-assistant-helm-chart
        version: 0.2.117
        valuesPath: k3s-cluster/kube-apps/values/homeassistant-values.yaml
  template:
    metadata:
      name: '{{name}}'
      namespace: argocd
    spec:
      project: default
      source:
        chart: '{{chart}}'
        repoURL: '{{repo}}'
        targetRevision: '{{version}}'
        helm:
          releaseName: '{{name}}'
          valueFiles:
          - $values/{{valuesPath}}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true