apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-helm-applications
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: ingress-nginx
        namespace: ingress-nginx
        chartPath: k3s-cluster/kube-apps/charts/ingress-nginx
        valuesPath: ../../values/ingress-nginx-values.yaml
      - name: longhorn
        namespace: longhorn-system
        chartPath: k3s-cluster/kube-apps/charts/longhorn
        valuesPath: ../../values/longhorn-values.yaml
      - name: metallb
        namespace: metallb-system
        chartPath: k3s-cluster/kube-apps/charts/metallb
        valuesPath: ../../values/metallb-values.yaml
      - name: homepage
        namespace: homepage
        chartPath: k3s-cluster/kube-apps/charts/homepage
        valuesPath: ../../values/homepage-values.yaml
      - name: homeassistant
        namespace: homeassistant
        chartPath: k3s-cluster/kube-apps/charts/home-assistant
        valuesPath: ../../values/homeassistant-values.yaml
  template:
    metadata:
      name: '{{name}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/BrandonCantrell/homelab.git
        targetRevision: develop
        path: '{{chartPath}}'
        helm:
          releaseName: '{{name}}'
          valueFiles:
          - '{{valuesPath}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
