apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-helm-applications
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: cert-manager
        namespace: cert-manager
        path: k3s-cluster/kube-apps/charts/cert-manager
        valuesPath: ../../values/cert-manager-values.yaml
      - name: loki
        namespace: monitoring
        path: k3s-cluster/kube-apps/charts/loki
        valuesPath: ../../values/loki-values.yaml
      - name: grafana
        namespace: monitoring
        chart: grafana
        repo: https://grafana.github.io/helm-charts
        version: 6.58.8
        valuesPath: k3s-cluster/kube-apps/values/grafana-values.yaml
      - name: prometheus
        namespace: monitoring
        chart: prometheus
        repo: https://prometheus-community.github.io/helm-charts
        version: 22.6.7
        valuesPath: k3s-cluster/kube-apps/values/prometheus-values.yaml
      - name: ingress-nginx
        namespace: ingress-nginx
        path: k3s-cluster/kube-apps/charts/ingress-nginx
        valuesPath: ../../values/ingress-nginx-values.yaml
      - name: longhorn
        namespace: longhorn-system
        path: k3s-cluster/kube-apps/charts/longhorn
        valuesPath: ../../values/longhorn-values.yaml
      - name: metallb-app
        namespace: metallb-system
        path: k3s-cluster/kube-apps/charts/metallb
        valuesPath: ../../values/metallb-values.yaml
      - name: homepage
        namespace: homepage
        path: k3s-cluster/kube-apps/charts/homepage
        valuesPath: ../../values/homepage-values.yaml
      - name: homeassistant
        namespace: homeassistant
        path: k3s-cluster/kube-apps/charts/home-assistant
        valuesPath: ../../values/homeassistant-values.yaml
  template:
    metadata:
      name: '{{name}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/BrandonCantrell/homelab.git
        targetRevision: develop
        path: '{{path}}'
        helm:
          releaseName: '{{name}}'
          valueFiles:
          - '{{valuesPath}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true