---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: manifests-applications
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: argocd
        namespace: argocd
        path: k3s-cluster/kube-apps/manifests/argocd
      - name: metallb-config
        namespace: metallb-system
        path: k3s-cluster/kube-apps/manifests/metallb-config
      - name: cert-manager-config
        namespace: cert-manager
        path: k3s-cluster/kube-apps/manifests/cert-manager-config
  template:
    metadata:
      name: '{{name}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/BrandonCantrell/homelab.git
        targetRevision: develop
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true